### ISSUE TITLE
Fatal error on the affiliate screen 

### ISSUE THREAD

**Issue by michaelbeil** [AffiliateWP/affiliatewp-store-credit#66] opened 2018-04-03 17:01 UTC
This fatal error causes affiliates to be missing. Notice how on the affiliate screen, it stops at the store credit column. 

Ticket: https://secure.helpscout.net/conversation/553741481/79620?folderId=634609/.

**Comment by michaelbeil** [comment] 2018-04-03 17:04
https://secure.helpscout.net/conversation/544941078/78558?folderId=205529

**Comment by amdrew** [comment] 2018-04-03 23:10
Will check it out

**Comment by amdrew** [comment] 2018-04-03 23:29
Replicated, will push out fix soon

**Comment by amdrew** [comment] 2018-04-03 23:43
The fatal error is being caused by the store credit option not being enabled from the Store Credit tab. 
Since it's not enabled, the store credit column on the affiliates page is trying to access a function in another file which isn't yet being loaded (there's a conditional that prevents other files from being loaded if store credit is turned off).

To fix, we'll move the `includes/admin/settings.php` file below the conditional check so it isn't loaded at all when store credit is disabled. This will result in the store credit column not showing when store credit is disabled, so any customer experiencing this issue will need to update their plugin, and then turn on store credit to use it.

**Comment by amdrew** [comment] 2018-04-03 23:46
Fixed via https://github.com/AffiliateWP/affiliatewp-store-credit/commit/6c7981a2776574dbce7f646ce2abdc9f918d7688

**Closed by amdrew** 2018-04-03 23:46 UTC
Labels: Has HS to-notify, bug
